package test // 包名：仅用于逻辑分区，和目录结构无关，同一包下的函数可以相互使用

import java.util.List; // 导入类
import com.lin.ch02.entity.Customer;

rule "rule1"
     /*
     date-expires
     属性特点
     1.与date-effective相反，该属性是设置规则的有效期的
     2.如果当前系统时间小于该值，规则才会执行
     3.日期格式为：dd-MMM-yyyy，如果是2019-08-31，则应该写成：31-Aug-2019，或者：31-八月-2019
     4.可在java代码中使用System.setProperty("drools.dateformat","yyyy-MM-dd");修改默认日期格式
    */
    date-expires "2019-09-02"
    when
        eval(true)
    then
        System.out.println("rule1 被执行了");
end